#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
TOTAL_MINUTES=10

PROJECT_ID="naorcr6k"
# The dataset the skill drafts to by default, so the smoke test checks the one
# a real session will use. `production` is opt-in by name, in the conversation.
DATASET="development"
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SKILL_DIR/../.." && pwd)"
ZIP="$SKILL_DIR/dist/authoring.zip"

# groq QUERY — run a GROQ query against $DATASET as the logged-in Sanity user.
groq() {
  (cd "$REPO_ROOT/packages/sanity" &&
    npx --no-install sanity documents query "$1" \
      --project-id "$PROJECT_ID" --dataset "$DATASET" --api-version 2025-08-15 2>/dev/null)
}

banner "Wire Claude Desktop for O3 authoring"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Build the skill ZIP" 1
say "The ZIP is a build artifact — never committed, so build it fresh."
(cd "$REPO_ROOT" && pnpm build:skill)
[[ -f "$ZIP" ]] || { warn "expected $ZIP — build failed"; exit 1; }
say "Built: $ZIP"
step "A Finder window is opening on it. Leave it — stage 3 drags from here."
open_url "$SKILL_DIR/dist"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Enable code execution" 1
say "Skills only appear in settings once code execution is on."
open_url "https://claude.ai/settings"
step "Settings → Capabilities → turn on code execution."
note "Already on? Nothing to do — carry on."
pause "Done?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Upload the skill" 2
say "Skills are account-level: uploading here reaches Desktop, web, and mobile."
open_url "https://claude.ai/settings"
step "Settings → Customize → Skills → Upload a skill."
step "Choose authoring.zip from the Finder window stage 1 opened."
note "Re-uploading the same ZIP replaces the installed version — that is how"
note "you ship a skill update. Voice and composition guidance are NOT in the"
note "ZIP; they live in the dataset and update with a git push + guidance:sync."
pause "Does authoring show up in the skills list?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Connect Sanity" 3
say "The connector is the hosted Sanity MCP. You OAuth as yourself; your Sanity"
say "role bounds what the skill can write. No token is ever shared."
open_url "https://claude.com/connectors/sanity"
step "Add the connector, then open Claude Desktop → Settings → Connectors."
step "Click Connect on Sanity and complete the OAuth login."
warn "Log in with GitHub. One email can map to several Sanity accounts, and"
warn "nick@o3world.com resolves through the GitHub provider on this project."
note "Sessions last about 7 days; a reconnect prompt later is normal, not a fault."
pause "Connected?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Smoke test" 3
say "Start a new Claude Desktop chat and paste this:"
printf '\n%s' "$DIM"
cat <<'PROMPT'
  Use the authoring skill against Sanity project naorcr6k, dataset
  development. Fetch the guidance documents, then fetch the full schema for
  the `insight` type. My thesis is "a wire-up is not working until something
  outside the app says so" — skip the brief's rounds and use it. Then create
  a throwaway draft insight titled "Desktop wire-up smoke test — delete me"
  with a one-line body. Report the document ID, the guidance keys you found,
  and one field description you read off the insight schema.
PROMPT
printf '%s\n' "$RESET"
note "Expect five guidance keys: o3-voice, o3-brand, o3-slop, o3-composition,"
note "o3-visual. Handing it a thesis is the brief's one override — without it,"
note "the skill is supposed to refuse to create anything."
pause "Claude says it created the draft?"

say "Checking the dataset from this side…"
DRAFTS=$(groq '*[_id in path("drafts.**") && _type == "insight"]{_id, title}' || true)
if [[ -z "$DRAFTS" || "$DRAFTS" == "[]" ]]; then
  warn "no draft insights found — Desktop did not reach the dataset."
  note "Most likely: the connector is not actually connected, or the OAuth"
  note "login landed on a Sanity account without write access to $PROJECT_ID."
  SKIPPED+=("smoke test — no draft insight reached $PROJECT_ID/$DATASET")
else
  printf '  %s✓ the draft is really there%s\n' "$GREEN" "$RESET"
  printf '%s\n' "$DRAFTS"
  if confirm "Delete the throwaway draft now?"; then
    for id in $(printf '%s' "$DRAFTS" | grep -oE 'drafts\.[A-Za-z0-9._-]+' || true); do
      if (cd "$REPO_ROOT/packages/sanity" &&
          npx --no-install sanity documents delete "$id" \
            --project-id "$PROJECT_ID" --dataset "$DATASET" >/dev/null 2>&1); then
        printf '  %s✓ deleted%s %s\n' "$GREEN" "$RESET" "$id"
      else
        SKIPPED+=("delete $id by hand in Studio")
      fi
    done
  else
    SKIPPED+=("discard the smoke-test draft in Studio")
  fi
fi

finish
note "Desktop is wired. Ask it to draft something and it will fetch the voice"
note "guide before it writes a word."
